apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: danielpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: danielpipelinesjavascriptdocker 
    spec:
      containers:
        - name: danielpipelinesjavascriptdocker 
          image: mycontainerregistry1demo.azurecr.io/danielpipelinesjavascriptdocker
          ports:
          - containerPort: 8080